version: "3.3"
services:

  tika:
    image: lexpredict/tika-server:latest
    ports:
      - 9999:9998
    configs:
    - source: tika_config_3
      target: /tika-config.xml
    networks:
      - net
    deploy:
      replicas: 3

networks:
  net:

configs:
  tika_config_3:
    file: ./tika-config.xml
